#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="$ROOT_DIR/VKTurnProxy/AppStoreConnect.env"
KEY_ID="${APPSTORE_KEY_ID:-}"
ISSUER_ID="${APPSTORE_ISSUER_ID:-}"
KEY_PATH="${APPSTORE_KEY_PATH:-}"
FORCE=0

usage() {
  cat <<'EOF'
Usage:
  scripts/configure-testflight-env.sh \
    --key-id <APPSTORE_KEY_ID> \
    --issuer-id <APPSTORE_ISSUER_ID> \
    --key-path </absolute/path/AuthKey_XXXXXXXXXX.p8> \
    [--output VKTurnProxy/AppStoreConnect.env] [--force]

Environment variable fallbacks:
  APPSTORE_KEY_ID
  APPSTORE_ISSUER_ID
  APPSTORE_KEY_PATH

The script writes a local ignored env file with mode 0600. It does not copy
the .p8 key and does not commit secrets.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --key-id)
      KEY_ID="${2:-}"
      shift 2
      ;;
    --issuer-id)
      ISSUER_ID="${2:-}"
      shift 2
      ;;
    --key-path)
      KEY_PATH="${2:-}"
      shift 2
      ;;
    --output)
      OUTPUT="${2:-}"
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 64
      ;;
  esac
done

if [[ -z "$KEY_ID" || -z "$ISSUER_ID" || -z "$KEY_PATH" ]]; then
  echo "ERROR: --key-id, --issuer-id, and --key-path are required." >&2
  usage >&2
  exit 64
fi

if [[ ! "$KEY_ID" =~ ^[A-Z0-9]{10}$ ]]; then
  echo "ERROR: APPSTORE_KEY_ID should be a 10-character App Store Connect key id." >&2
  exit 64
fi

if [[ ! "$ISSUER_ID" =~ ^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$ ]]; then
  echo "ERROR: APPSTORE_ISSUER_ID should be a UUID." >&2
  exit 64
fi

if [[ "$KEY_PATH" != /* ]]; then
  echo "ERROR: APPSTORE_KEY_PATH must be absolute: $KEY_PATH" >&2
  exit 64
fi

if [[ ! -f "$KEY_PATH" ]]; then
  echo "ERROR: App Store Connect .p8 key does not exist: $KEY_PATH" >&2
  exit 1
fi

if [[ "$(basename "$KEY_PATH")" != AuthKey_*.p8 ]]; then
  echo "WARN: key file name does not look like AuthKey_XXXXXXXXXX.p8: $KEY_PATH" >&2
fi

if [[ "$KEY_PATH" == "$ROOT_DIR/"* ]]; then
  echo "WARN: .p8 key is inside the repository. Keep it ignored and do not commit it." >&2
fi

case "$OUTPUT" in
  /*) ;;
  *) OUTPUT="$ROOT_DIR/$OUTPUT" ;;
esac

if [[ -e "$OUTPUT" && "$FORCE" != 1 ]]; then
  echo "ERROR: $OUTPUT already exists. Use --force to overwrite." >&2
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT")"
tmp="$(mktemp "$OUTPUT.tmp.XXXXXX")"
chmod 600 "$tmp"
cat > "$tmp" <<EOF
# Local App Store Connect API credentials for release.sh.
# Generated by scripts/configure-testflight-env.sh.
# Do not commit this file or the .p8 private key.

APPSTORE_KEY_ID=$KEY_ID
APPSTORE_ISSUER_ID=$ISSUER_ID
APPSTORE_KEY_PATH=$KEY_PATH
EOF
mv "$tmp" "$OUTPUT"
chmod 600 "$OUTPUT"

if git -C "$ROOT_DIR" check-ignore -q "$OUTPUT"; then
  ignored="yes"
else
  ignored="no"
fi

printf 'Wrote %s\n' "$OUTPUT"
printf 'File mode: %s\n' "$(stat -f%Lp "$OUTPUT" 2>/dev/null || stat -c%a "$OUTPUT")"
printf 'Git ignored: %s\n' "$ignored"
printf 'Next: ALLOW_EXTERNAL_BLOCKERS=1 scripts/preflight-testflight.sh\n'
